export type Restaurant = {
  id: string;
  owner_id: string;
  restaurant_name: string | null;
  restaurant_name_ar?: string | null;
  slug: string | null;
  email: string | null;
  phone: string | null;
  logo_url: string | null;
  cover_url?: string | null;
  currency: string;
  timezone: string;
  is_active?: boolean;
  subscription_plan?: string | null;
  tagline_en?: string | null;
  tagline_ar?: string | null;
  address_en?: string | null;
  address_ar?: string | null;
  opening_hours?: string | null;
  whatsapp_number?: string | null;
  social_instagram?: string | null;
  social_facebook?: string | null;
  social_tiktok?: string | null;
  delivery_enabled?: boolean;
  delivery_notes?: string | null;
  theme_primary_color?: string | null;
  languages?: string[] | null;
  show_prices?: boolean;
  bilingual_menu?: boolean;
  whatsapp_orders?: boolean;
  table_qr_ordering?: boolean;
  show_nutrition?: boolean;
  dark_mode_default?: boolean;
  onboarding_completed?: boolean;
  onboarding_step?: number;
  restaurant_type?: string | null;
  owner_name?: string | null;
  website?: string | null;
  city?: string | null;
  country?: string | null;
  google_maps_url?: string | null;
  preferred_language?: string | null;
  favicon_url?: string | null;
  menu_accent_color?: string | null;
  font_style?: string | null;
  about_us?: string | null;
  cuisine_type?: string | null;
  holiday_schedule?: string | null;
  gallery_urls?: string[] | null;
  branches?: unknown[] | null;
  delivery_platforms?: unknown[] | null;
  tax_number?: string | null;
  commercial_registration?: string | null;
  vat_number?: string | null;
  seo_title?: string | null;
  seo_description?: string | null;
  seo_keywords?: string | null;
  og_image_url?: string | null;
  reservations_enabled?: boolean;
  online_ordering_enabled?: boolean;
  kitchen_display_enabled?: boolean;
  tax_rate?: number;
  service_charge_rate?: number;
  created_at: string;
  updated_at: string;
};
