export interface RestaurantSettings {
  nameEn: string;
  nameAr: string;
  taglineEn: string;
  taglineAr: string;
  phone: string;
  whatsapp: string;
  email: string;
  addressEn: string;
  addressAr: string;
  openingHours: string;
  holidaySchedule: string;
  logoUrl: string;
  coverUrl: string;
  galleryUrls: string[];
  aboutUs: string;
  cuisineType: string;
  branches: string[];
  socialInstagram: string;
  socialFacebook: string;
  socialTiktok: string;
  website: string;
  googleMapsUrl: string;
  deliveryEnabled: boolean;
  deliveryNotes: string;
  deliveryPlatforms: string[];
  taxNumber: string;
  commercialRegistration: string;
  vatNumber: string;
  currency: string;
  timezone: string;
  seoTitle: string;
  seoDescription: string;
  seoKeywords: string;
  ogImageUrl: string;
  themePrimaryColor: string;
  languages: string[];
  showPrices: boolean;
  bilingualMenu: boolean;
  whatsappOrders: boolean;
  tableQrOrdering: boolean;
  showNutrition: boolean;
  darkModeDefault: boolean;
}

export const defaultSettings: RestaurantSettings = {
  nameEn: "",
  nameAr: "",
  taglineEn: "",
  taglineAr: "",
  phone: "",
  whatsapp: "",
  email: "",
  addressEn: "",
  addressAr: "",
  openingHours: "",
  holidaySchedule: "",
  logoUrl: "",
  coverUrl: "",
  galleryUrls: [],
  aboutUs: "",
  cuisineType: "",
  branches: [],
  socialInstagram: "",
  socialFacebook: "",
  socialTiktok: "",
  website: "",
  googleMapsUrl: "",
  deliveryEnabled: false,
  deliveryNotes: "",
  deliveryPlatforms: [],
  taxNumber: "",
  commercialRegistration: "",
  vatNumber: "",
  currency: "KWD",
  timezone: "Asia/Kuwait",
  seoTitle: "",
  seoDescription: "",
  seoKeywords: "",
  ogImageUrl: "",
  themePrimaryColor: "#d4af37",
  languages: ["en", "ar"],
  showPrices: true,
  bilingualMenu: true,
  whatsappOrders: false,
  tableQrOrdering: false,
  showNutrition: false,
  darkModeDefault: true,
};
